import { createFileRoute, Link } from "@tanstack/react-router";
import { useState, useEffect } from "react";
import { motion } from "framer-motion";
import { FileText, Download, Brain, Plus, Calendar, FlaskConical, Atom, BookOpen } from "lucide-react";
import { Button } from "@/components/ui/button";
import { supabase } from "@/integrations/supabase/client";
import { EXPERIMENTS } from "@/data/experiments";
import { toast } from "sonner";

export const Route = createFileRoute("/_app/reports")({
  component: Reports,
});

type Report = {
  id: string;
  title: string;
  subject?: string;
  created_at: string;
  experiment_slug?: string;
};

function Reports() {
  const [reports, setReports] = useState<Report[]>([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [selected, setSelected] = useState<string | null>(null);

  useEffect(() => {
    (async () => {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) { setLoading(false); return; }
      const { data } = await supabase.from("reports").select("*").eq("user_id", user.id).order("created_at", { ascending: false });
      setReports((data as Report[]) ?? []);
      setLoading(false);
    })();
  }, []);

  const generateReport = async () => {
    if (!selected) return;
    setGenerating(true);
    await new Promise((r) => setTimeout(r, 1200));
    const exp = EXPERIMENTS.find((e) => e.slug === selected);
    if (!exp) { setGenerating(false); return; }

    const reportContent = [
      `LABORATORY REPORT — ${exp.title.toUpperCase()}`,
      "=".repeat(60),
      "",
      `Date: ${new Date().toLocaleDateString()}`,
      `Subject: ${exp.subject.charAt(0).toUpperCase() + exp.subject.slice(1)}`,
      `Level: ${exp.level === "o_level" ? "O-Level" : "A-Level"}`,
      "",
      "─".repeat(60),
      "AIM",
      "─".repeat(60),
      exp.description,
      "",
      "─".repeat(60),
      "APPARATUS AND MATERIALS",
      "─".repeat(60),
      (exp.tools ?? []).map((t, i) => `${i + 1}. ${t}`).join("\n"),
      "",
      "─".repeat(60),
      "METHOD",
      "─".repeat(60),
      (exp.steps ?? []).map((s, i) => `${i + 1}. ${s}`).join("\n"),
      "",
      "─".repeat(60),
      "OBSERVATIONS AND RESULTS",
      "─".repeat(60),
      exp.expectedResults,
      "",
      "─".repeat(60),
      "CONCLUSION",
      "─".repeat(60),
      `The experiment successfully demonstrated the principles of ${exp.title.toLowerCase()}. The results obtained were consistent with the theoretical predictions and ZIMSEC curriculum requirements for ${exp.level === "o_level" ? "Ordinary Level" : "Advanced Level"} ${exp.subject}.`,
      "",
      "─".repeat(60),
      "SAFETY NOTES",
      "─".repeat(60),
      exp.safetyNotes,
      "",
      "─".repeat(60),
      "Generated by FundoLabs AI · fundolabs.co.zw",
    ].join("\n");

    const blob = new Blob([reportContent], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${selected}-lab-report.txt`;
    a.click();
    URL.revokeObjectURL(url);

    const { data: { user } } = await supabase.auth.getUser();
    if (user) {
      const { data: newReport } = await supabase.from("reports").insert({
        user_id: user.id,
        title: `${exp.title} Lab Report`,
        content: reportContent,
      }).select("id, title, created_at").maybeSingle();
      if (newReport) {
        setReports((prev) => [{ ...newReport, subject: exp.subject, experiment_slug: exp.slug }, ...prev]);
      }
    }

    setGenerating(false);
    toast.success("Lab report generated and downloaded!");
  };

  return (
    <div className="max-w-4xl space-y-8">
      <div>
        <h1 className="text-3xl font-bold mb-2 flex items-center gap-3">
          <FileText className="h-8 w-8 text-primary" /> Lab Reports
        </h1>
        <p className="text-muted-foreground">AI-generated lab reports for your experiments. Download as text files ready for submission.</p>
      </div>

      <div className="glass-card rounded-2xl p-6">
        <h2 className="text-lg font-semibold mb-4 flex items-center gap-2">
          <Brain className="h-5 w-5 text-accent" /> Generate New Report
        </h2>
        <div className="space-y-4">
          <div>
            <label className="text-sm text-muted-foreground mb-2 block">Select Experiment</label>
            <select
              value={selected ?? ""}
              onChange={(e) => setSelected(e.target.value || null)}
              className="w-full glass-card border border-white/10 rounded-xl px-4 py-3 text-sm focus:outline-none focus:border-primary/40 transition bg-transparent"
            >
              <option value="">Choose an experiment…</option>
              {EXPERIMENTS.map((exp) => (
                <option key={exp.slug} value={exp.slug} style={{ background: "#1a1f3a" }}>
                  [{exp.level === "o_level" ? "O-Level" : "A-Level"}] {exp.title} ({exp.subject})
                </option>
              ))}
            </select>
          </div>
          <Button
            onClick={generateReport}
            disabled={!selected || generating}
            className="bg-gradient-to-r from-primary to-accent text-primary-foreground glow-primary"
          >
            {generating ? (
              <><Brain className="h-4 w-4 mr-2 animate-spin" /> Generating report…</>
            ) : (
              <><Plus className="h-4 w-4 mr-2" /> Generate AI Lab Report</>
            )}
          </Button>
        </div>
      </div>

      <div>
        <h2 className="text-lg font-semibold mb-4">Your Reports ({reports.length})</h2>
        {loading ? (
          <div className="space-y-3">
            {[...Array(3)].map((_, i) => <div key={i} className="glass-card rounded-2xl h-20 animate-pulse" />)}
          </div>
        ) : reports.length === 0 ? (
          <div className="glass-card rounded-2xl p-10 text-center">
            <FileText className="h-10 w-10 mx-auto mb-3 text-muted-foreground/30" />
            <p className="text-muted-foreground mb-4">No reports yet. Generate your first AI lab report above!</p>
          </div>
        ) : (
          <div className="space-y-3">
            {reports.map((report, i) => (
              <motion.div
                key={report.id}
                initial={{ opacity: 0, y: 12 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: i * 0.06 }}
                className="glass-card rounded-2xl p-5 flex items-center gap-4"
              >
                <div className="h-11 w-11 rounded-xl bg-gradient-to-br from-primary/20 to-accent/20 flex items-center justify-center flex-shrink-0">
                  {report.subject === "chemistry" ? <FlaskConical className="h-5 w-5 text-primary" /> : <Atom className="h-5 w-5 text-primary" />}
                </div>
                <div className="flex-1 min-w-0">
                  <div className="font-semibold truncate">{report.title}</div>
                  <div className="flex items-center gap-3 text-xs text-muted-foreground mt-0.5">
                    <span className="flex items-center gap-1"><Calendar className="h-3 w-3" />{new Date(report.created_at).toLocaleDateString()}</span>
                    {report.subject && <span className="capitalize">{report.subject}</span>}
                  </div>
                </div>
                <div className="flex gap-2">
                  {report.experiment_slug && (
                    <Link to="/labs/$slug" params={{ slug: report.experiment_slug }} className="glass rounded-lg px-3 py-1.5 text-xs text-muted-foreground hover:text-foreground transition flex items-center gap-1.5">
                      <BookOpen className="h-3 w-3" /> View
                    </Link>
                  )}
                  <button className="glass rounded-lg px-3 py-1.5 text-xs text-muted-foreground hover:text-foreground transition flex items-center gap-1.5">
                    <Download className="h-3 w-3" /> Download
                  </button>
                </div>
              </motion.div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
